import { notFound } from "next/navigation";
import { getQuote, quoteTotal } from "@/lib/services/quotes";
import { getWorkspace } from "@/lib/services/workspace";
import { formatMoney, formatDate } from "@/lib/format";
import { DocumentShell } from "@/components/documents/DocumentShell";

export const dynamic = "force-dynamic";

export default async function QuoteDocumentPage({ params }: { params: { id: string } }) {
  const [quote, workspace] = await Promise.all([getQuote(params.id), getWorkspace()]);
  if (!quote) notFound();

  return (
    <DocumentShell
      workspace={workspace}
      docType="Quotation"
      reference={quote.reference}
      dateLabel={formatDate(quote.createdAt)}
      backHref="/quotes"
    >
      <div className="mb-6">
        <div className="label-caps mb-1">Prepared for</div>
        <div className="text-ink">{quote.clientName}</div>
      </div>

      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-line text-left text-muted">
            <th className="py-2">Commodity</th>
            <th className="py-2">Grade</th>
            <th className="py-2 text-right">Quantity</th>
            <th className="py-2 text-right">Unit price</th>
            <th className="py-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {quote.lines.map((l) => (
            <tr key={l.id} className="border-b border-line">
              <td className="py-2 text-ink">{l.commodityName}</td>
              <td className="py-2 text-muted">{l.grade ?? "-"}</td>
              <td className="py-2 text-right text-ink">
                {l.quantity} {l.unit}
              </td>
              <td className="py-2 text-right text-ink">{formatMoney(l.unitPrice)}</td>
              <td className="py-2 text-right text-ink">{formatMoney(l.quantity * l.unitPrice)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr>
            <td colSpan={4} className="py-3 text-right font-medium text-ink">
              Total
            </td>
            <td className="py-3 text-right font-display text-lg font-semibold text-ink">
              {formatMoney(quoteTotal(quote.lines))}
            </td>
          </tr>
        </tfoot>
      </table>

      <div className="mt-6 grid gap-4 text-sm sm:grid-cols-2">
        {quote.deliveryTerms ? (
          <div>
            <div className="label-caps mb-1">Delivery terms</div>
            <div className="text-ink">{quote.deliveryTerms}</div>
          </div>
        ) : null}
        {quote.validUntil ? (
          <div>
            <div className="label-caps mb-1">Valid until</div>
            <div className="text-ink">{formatDate(quote.validUntil)}</div>
          </div>
        ) : null}
      </div>

      {quote.notes ? (
        <div className="mt-6 text-sm">
          <div className="label-caps mb-1">Notes</div>
          <div className="prose-simple text-ink">{quote.notes}</div>
        </div>
      ) : null}

      <p className="mt-8 text-xs text-muted">
        This quotation was generated by {workspace.name}. Prices are quoted in GHS and are valid for the
        period stated above.
      </p>
    </DocumentShell>
  );
}
