import { notFound } from "next/navigation";
import { getInvoice } from "@/lib/services/invoices";
import { getWorkspace } from "@/lib/services/workspace";
import { formatMoney, formatDate } from "@/lib/format";
import { DocumentShell } from "@/components/documents/DocumentShell";

export const dynamic = "force-dynamic";

export default async function InvoiceDocumentPage({ params }: { params: { id: string } }) {
  const [invoice, workspace] = await Promise.all([getInvoice(params.id), getWorkspace()]);
  if (!invoice) notFound();

  const outstanding = invoice.amount - invoice.paidAmount;

  return (
    <DocumentShell
      workspace={workspace}
      docType="Invoice"
      reference={invoice.reference}
      dateLabel={formatDate(invoice.createdAt)}
      backHref="/invoices"
    >
      <div className="mb-6 flex justify-between">
        <div>
          <div className="label-caps mb-1">Billed to</div>
          <div className="text-ink">{invoice.clientName}</div>
        </div>
        <div className="text-right">
          {invoice.dueDate ? (
            <div>
              <div className="label-caps mb-1">Due</div>
              <div className="text-ink">{formatDate(invoice.dueDate)}</div>
            </div>
          ) : null}
          {invoice.creditTerms ? <div className="mt-2 text-sm text-muted">{invoice.creditTerms}</div> : null}
        </div>
      </div>

      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-line text-left text-muted">
            <th className="py-2">Description</th>
            <th className="py-2 text-right">Quantity</th>
            <th className="py-2 text-right">Unit price</th>
            <th className="py-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.lines.map((l) => (
            <tr key={l.id} className="border-b border-line">
              <td className="py-2 text-ink">{l.description}</td>
              <td className="py-2 text-right text-ink">
                {l.quantity} {l.unit}
              </td>
              <td className="py-2 text-right text-ink">{formatMoney(l.unitPrice)}</td>
              <td className="py-2 text-right text-ink">{formatMoney(l.quantity * l.unitPrice)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-4 ml-auto w-64 space-y-1 text-sm">
        <div className="flex justify-between">
          <span className="text-muted">Total</span>
          <span className="text-ink">{formatMoney(invoice.amount)}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-muted">Paid</span>
          <span className="text-ink">{formatMoney(invoice.paidAmount)}</span>
        </div>
        <div className="flex justify-between border-t border-line pt-1 font-medium">
          <span className="text-ink">Outstanding</span>
          <span className="font-display text-lg text-ink">{formatMoney(outstanding)}</span>
        </div>
      </div>

      {invoice.notes ? (
        <div className="mt-6 text-sm">
          <div className="label-caps mb-1">Notes</div>
          <div className="prose-simple text-ink">{invoice.notes}</div>
        </div>
      ) : null}

      <p className="mt-8 text-xs text-muted">Generated by {workspace.name}. Amounts in GHS.</p>
    </DocumentShell>
  );
}
